services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  node:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - postgres